=== clefego/ELE-PiAgent-CircleCI/AFClient_2.10.7.283/SetupDialogs.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="SetupWizardXml" nillable="true" type="SetupWizardXml" />
  <xs:complexType name="SetupWizardXml">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Module" type="ModuleElement" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ModuleElement">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Service" type="ServiceElement" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="InUseCheck" type="InUseCheckElement" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Variable" type="VariableElement" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Feature" type="FeatureElement" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ServiceElement">
    <xs:complexContent mixed="false">
      <xs:extension base="CommonAttributes">
        <xs:attribute name="NameMask" type="xs:string" />
        <xs:attribute name="Action" type="ActionEnum" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="CommonAttributes">
    <xs:attribute name="Condition" type="ConditionEnum" use="required" />
    <xs:attribute name="ConditionData" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="ConditionEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="OS32Bit" />
      <xs:enumeration value="OS64Bit" />
      <xs:enumeration value="PINSNode" />
      <xs:enumeration value="ComponentInstalled" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="VariableElement">
    <xs:complexContent mixed="false">
      <xs:extension base="CommonAttributes">
        <xs:attribute name="Name" type="xs:string" />
        <xs:attribute name="MSIProperty" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="InUseCheckElement">
    <xs:complexContent mixed="false">
      <xs:extension base="CommonAttributes">
        <xs:attribute name="Path" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="ActionEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MSIStops_WizardEnusuresStarted" />
      <xs:enumeration value="WizardStops_WizardEnusuresStarted" />
      <xs:enumeration value="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="FeatureElement">
    <xs:attribute name="Name" type="FeatureEnum" use="required" />
  </xs:complexType>
  <xs:simpleType name="FeatureEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ReadOnlyUniInt" />
      <xs:enumeration value="ReadWriteUniInt" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== clefego/ELE-PiAgent-CircleCI/AFClient_2.10.7.283/SetupDialogs.xml
<?xml version="1.0" encoding="utf-8"?>
<SetupWizardXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="./SetupDialogs.xsd">
  <!--       "{FFB43E28-15AA-4A82-8E79-A52DBC197F1B}" is upgrade code for 64-bit PI Data Archive MSI-->
  <Module Id="{FFB43E28-15AA-4A82-8E79-A52DBC197F1B}">
    <Service NameMask="pinetmgr" Action="WizardStops_WizardEnusuresStarted" Condition="ComponentInstalled" ConditionData="{E6EE4D3C-8DF7-4109-9A34-5AAC2C6652F1}" />
    <Service NameMask="pimsgss" Action="WizardStops_WizardEnusuresStarted" Condition="ComponentInstalled" ConditionData="{ABA14D21-C9C5-4A55-8345-A797BC7C5756}" />
    <!--Conditional restarts -->
    <Service NameMask="pilicmgr" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{D000DAD4-3A6E-49CB-A2E7-53E4CEB03855}" />
    <Service NameMask="pibasess" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{223A7BE0-3658-4291-8366-E7EB169535D1}" />
    <Service NameMask="pisnapss" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{EF907B43-E78B-4BA7-8D9A-CF0FE24DB07A}" />
    <Service NameMask="piarchss" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{4B1A3997-C2AF-4D95-9014-ADC5C9940AED}" />
    <Service NameMask="piupdmgr" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{01756001-CA5A-46E6-8213-8B6432777D0B}" />
    <Service NameMask="piaflink" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{5E5D46E4-D2F4-46AD-A5CE-981FB9603541}" />
    <Service NameMask="pibackup" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{A0456F5C-CA49-4A3C-8A86-A57526F8BCCD}" />
    <Service NameMask="pipeschd" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{4F520900-2BE8-4C18-BCC1-A11C7907D369}" />
    <Service NameMask="pisqlss" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{2C118E51-408C-4862-A161-94C346AC4065}" />
    <Service NameMask="pitotal" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{37997ECF-BED5-498A-8633-BC1379A8474E}" />
    <Service NameMask="pialarm" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{7C73118F-0B86-4E42-89C2-5DC19C288E81}" />
    <Service NameMask="pibatch" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{CA111109-AF4B-4B02-B010-DA229CF78F86}" />
    <Service NameMask="random" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{ECEE5446-EAB2-4802-81DD-18C7B36D4B5B}" />
    <Service NameMask="rmp_sk" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{2501D7ED-C428-4ACC-829C-2568CB98804D}" />
    <Service NameMask="pibagen" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{C27F8171-6B88-4F73-9640-1CF0ED019F64}" />
    <Service NameMask="piperfmon_basic*" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{BA93481C-3E28-4DD2-9C93-7FB6D3DB17D6}" />
    <Service NameMask="piperfmon*" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{9020B0A2-616A-492F-9C5B-93803549613B}" />
    <Service NameMask="piping_basic*" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{F8F56B14-85E9-4961-A963-C4ABB3E00081}" />
    <Service NameMask="piping*" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{B1E30C9F-9134-45A1-A85F-28944A657818}" />
    <Service NameMask="pisnmp_basic*" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{A1A2DE26-C556-4386-8405-5031F05EE2FB}" />
    <Service NameMask="pisnmp*" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{434F8DC4-63D6-4A32-95F3-0C5D99F2A142}" />
    <Service NameMask="PIIntStatus*" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{D237A65A-E9D1-4CCD-B4EE-0C2E4BA8925A}" />
    <Service NameMask="PITCPResp*" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="ComponentInstalled" ConditionData="{7BFA637B-160F-4E15-A923-BAA05E868288}" />
    <!--                  {DDDFBDB7-D3B5-40EA-BE3C-5866DAB5AF58} is component guid for pictrdll.dll (32-bit)-->
    <!--<InUseCheck Path="{DDDFBDB7-D3B5-40EA-BE3C-5866DAB5AF58}" Condition="None"/>-->
    <!--                  {42D518AA-C7A0-47B4-8439-BE2AC16CAD6E} is component guid for pictrdll.dll (64-bit)-->
    <!--<InUseCheck Path="{42D518AA-C7A0-47B4-8439-BE2AC16CAD6E}" Condition="None"/>-->
    <!--              {C848D21E-EF38-4418-B7BF-4B30AFE2BDBE} is component guid for pigetmsg.exe (64-bit)-->
    <InUseCheck Path="{C848D21E-EF38-4418-B7BF-4B30AFE2BDBE}" Condition="None" />
    <!--              {172D8725-02AE-4032-8E9C-890F42112F17} is component guid for piconfig.exe (64-bit)-->
    <InUseCheck Path="{172D8725-02AE-4032-8E9C-890F42112F17}" Condition="None" />
    <!--              {814E7B8A-9371-4326-BEA1-2E42493084BA} is component guid for piartool.exe (64-bit)-->
    <InUseCheck Path="{814E7B8A-9371-4326-BEA1-2E42493084BA}" Condition="None" />
    <!--              {EC14E762-369D-40E6-AA58-A52700C77000} is component guid for pilistupd.exe (64-bit)-->
    <InUseCheck Path="{EC14E762-369D-40E6-AA58-A52700C77000}" Condition="None" />
    <!--              {2DB19BE1-B15E-45DD-A77A-675A84A89731} is component guid for apisnap.exe (64-bit)-->
    <InUseCheck Path="{2DB19BE1-B15E-45DD-A77A-675A84A89731}" Condition="None" />
    <!--              {04BB442F-AAD1-432F-8EA6-8C91A4EACE7C} is component guid for ipisql.exe (64-bit)-->
    <InUseCheck Path="{04BB442F-AAD1-432F-8EA6-8C91A4EACE7C}" Condition="None" />
    <!--              {F380229C-837C-4FC6-AA10-1D5FB1A0B93E} is component guid for pipetest.exe (64-bit)-->
    <InUseCheck Path="{F380229C-837C-4FC6-AA10-1D5FB1A0B93E}" Condition="None" />
    <!--              {1AEEEE4D-EF05-49EF-ACB7-6A94C5FA1917} is component guid for pisetpass.exe (64-bit)-->
    <InUseCheck Path="{1AEEEE4D-EF05-49EF-ACB7-6A94C5FA1917}" Condition="None" />
    <Variable Name="PI3INSTALLATIONPATH" MSIProperty="INSTALLDIR" Condition="None" />
    <Variable Name="DEFAULTAFSERVER" MSIProperty="AF_SERVER" Condition="None" />
    <Variable Name="PI3LICENSE" MSIProperty="LICDIR" Condition="None" />
    <Variable Name="PI3ARCHIVEPATH" MSIProperty="ARCHIVEDATDIR" Condition="None" />
    <Variable Name="PI3FUTUREARCHIVEPATH" MSIProperty="FUTUREARCHIVEDATDIR" Condition="None" />
    <Variable Name="PI3EVENTQUEUEPATH" MSIProperty="EVENTQUEUEDIR" Condition="None" />
    <Variable Name="PI3OFFLINEBACKUPDIR" MSIProperty="BACKUPDIR" Condition="None" />
  </Module>
  <!--       "PINS" corresponds to a setup wrapper dll named PINS.DLL-->
  <Module Id="PINS">
    <Service NameMask="pinetmgr" Action="MSIStops_WizardEnusuresStarted" Condition="None" />
    <Service NameMask="pimsgss" Action="MSIStops_WizardEnusuresStarted" Condition="None" />
    <!--              pigetmsg.exe (32-bit)-->
    <InUseCheck Path="%pihome%\adm\pigetmsg.exe" Condition="None" />
    <!--              pigetmsg.exe (64-bit)-->
    <InUseCheck Path="%pihome64%\adm\pigetmsg.exe" Condition="OS64Bit" />
    <Variable Name="PIHOME" MSIProperty="INSTALLDIR" Condition="None" />
    <Variable Name="PIHOME64" MSIProperty="INSTALLDIR64" Condition="OS64Bit" />
  </Module>
  <Module Id="pisdk.msi">
    <!--               pinetmgr is stopped only if the 32-bit pinetmgr is installed on a PINS node -->
    <Service NameMask="pinetmgr" Action="WizardStops_WizardEnusuresStarted" Condition="ComponentInstalled" ConditionData="{3532B7B6-A9DA-11D4-B939-00C04F124D3D}" />
    <!--               pimsgss always restarted because of pimdf.dat-->
    <Service NameMask="pimsgss" Action="WizardStops_WizardEnusuresStarted" Condition="None" />
    <Service NameMask="bufserv" Action="WizardStops_WizardEnusuresStartedIfRunningBeforeInstall" Condition="None" />
    <Service NameMask="pilogsrv" Action="WizardStops_WizardEnusuresStarted" Condition="None" />
    <!--              {BC624D7A-D5FF-11D4-B95B-00C04F124D3D} is the component guid of "%PIHOME%\PISDK\pisdk.dll-->
    <InUseCheck Path="{BC624D7A-D5FF-11D4-B95B-00C04F124D3D}" Condition="None" />
    <!--              {BC624D7C-D5FF-11D4-B95B-00C04F124D3D} is the component guid of pisdkcommon.dll-->
    <InUseCheck Path="{BC624D7C-D5FF-11D4-B95B-00C04F124D3D}" Condition="None" />
    <!--              %systemroot%\system32\piapi32.dll or component {04518E17-AC6B-11D4-B948-00C04F124D3D} sometimes pre-dates Windows Installer components. Use full paths as well as component. -->
    <InUseCheck Path="%systemroot%\system32\piapi32.dll" Condition="OS32Bit" />
    <InUseCheck Path="{04518E17-AC6B-11D4-B948-00C04F124D3D}" Condition="None" />
    <!--              {19510979-AE83-11D4-B948-00C04F124D3D} is the component guid of apisnap.exe-->
    <InUseCheck Path="{19510979-AE83-11D4-B948-00C04F124D3D}" Condition="None" />
